11/06/2023 18:49:42 - INFO - __main__ - ***** Running training *****
11/06/2023 18:49:42 - INFO - __main__ -   Num examples = 151736
11/06/2023 18:49:42 - INFO - __main__ -   Num Epochs = 20
11/06/2023 18:49:42 - INFO - __main__ -   Instantaneous batch size per device = 16
11/06/2023 18:49:42 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 96
11/06/2023 18:49:42 - INFO - __main__ -   Gradient Accumulation steps = 1
11/06/2023 18:49:42 - INFO - __main__ -   Total optimization steps = 31620

  0%|                                                                                                     | 1/31620 [00:05<45:23:03,  5.17s/it]11/06/2023 18:49:47 - INFO - __main__ -   Step: 1, LR: 2.1089630931458703e-08, Loss: 5.133994102478027
  0%|                                                                                                     | 2/31620 [00:09<39:15:45,  4.47s/it]11/06/2023 18:49:51 - INFO - __main__ -   Step: 2, LR: 4.2179261862917406e-08, Loss: 5.210137367248535
  0%|                                                                                                     | 3/31620 [00:13<37:19:02,  4.25s/it]11/06/2023 18:49:55 - INFO - __main__ -   Step: 3, LR: 6.32688927943761e-08, Loss: 5.106597423553467
  0%|                                                                                                     | 4/31620 [00:17<36:25:01,  4.15s/it]11/06/2023 18:49:59 - INFO - __main__ -   Step: 4, LR: 8.435852372583481e-08, Loss: 5.220107078552246
11/06/2023 18:50:00 - INFO - __main__ - Start doing evaluation at step: 4
Traceback (most recent call last):                                                                                       | 0/4 [00:00<?, ?it/s]
  File "./open_instruct/open_instruct/finetune_val.py", line 913, in <module>
    main()
  File "./open_instruct/open_instruct/finetune_val.py", line 834, in main
    scores_metric.add_batch(predictions=batch_predict, references=val_gt, split="val")
  File "/local1/ponienkung/miniconda3/envs/tulu/lib/python3.8/site-packages/datasets/metric.py", line 491, in add_batch
    raise ValueError(f"Bad inputs for metric: {bad_inputs}. All required inputs are {list(self.features)}")
ValueError: Bad inputs for metric: ['split']. All required inputs are ['predictions', 'references']